doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                Adshares\AdsManager:
                    is_bundle: false
                    type: annotation
#                    dir: '%kernel.project_dir%/src/Document'
                    dir: "%kernel.project_dir%/config/doctrine"
                    prefix: Adshares\AdsManager\Document\
                    alias: AdsManager
