jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            entities:
                namespace_prefix: Adshares\AdsOperator\Document
                path: "%kernel.root_dir%/../config/serializer"
            ads:
                namespace_prefix: Adshares\Ads\Entity
                path: "%kernel.root_dir%/../config/serializer/ads"
