# Project language
language: php
sudo: false

# PHP version
php:
  - 7.2

env:
  global:
    - DRIVER_VERSION=1.5.0
    - SYMFONY_VERSION="4.0.*"

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - ${HOME}/.composer/cache/files
    - ${HOME}/php-ext

services:
  - mongodb

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "Dk2MQCW5SDUS6QWwoNc+4cmIgbWiHamavBWbgn/jaCHlBhOs62Zq+Ru+3CztK0B44E8lweLWWj3Ugc6kBq6m2rC3ib+o/4wiN4kego+99EuOV9BxJFkyMhP4QCWCXw4qbylIsS7wlrRxTQ1wUtmHW5V2R3NhJhV7rQJWaPXN4/H0lazyPP6xKGOGRpB8WSwb02zN92G0lm/VOIvzn0HGBBS34TE6GVPr1Jap5cZ2nPuwS446rPdOmf5Uu+VLS0z0JC3tPUr6kzOW3R81TlP8x9DFJY4ijbfirrjnoyuNn+D1HvELgnQd8uSrb1MwSota8qRwOTD8L8frZ+tKCPQOhV6VyxyQeEwQggALNnHQPLbuGua6KMgl9qgbjYVaTijPOrRt5PlgiUFHDFPMBFa3J/DYwsGOaB4WOvsPjC76etugwNACgnteyCe3L2Vg4xU7Pd1CCzXQ4FXC593CcBf4R+CP1QWdej1Q/MP6n5KFGpvIJwAmcNWnBpqvH2HUEl2PDlg4JDEBOQVLRpO/zbzRJCnb1CFl4xFTZZ4s89liZNz2a+Nw9nRPlvRLGyof0HlTzcnOvykRw1i6sJUGaP1HbcaK6FPbE1K+X9ri1kL8H5cKzPNZ68PNdLaQG3Z3BJ/QiAEkbT8JHr/R2Qyh/YZyT6y1XvKkjA/40AXnx7A8JaI="
    github_token:
      secure: "WZwVh8X2UzQa/n0riLibSjgpAegEZsNbfIwv/BFJF/OAS+yuAzN9H9vekSFwC2KHvsDz9V2aJ0wBwamznNOgTa696qTvHGOWqzkPDDO4DnN+hEq20nXWGNwzXZ3YdONEjyN8cKIIvBCTijH9RN8AgFPundclib0KX66iOIkaj3KyijHgL+KBnI5OEAYzWVygoEF/zNJ2WrtinyrC3E8VXM2osFXXpTyDpS3/LA3x/zVQ4RaSnJjVdXbvfMM2C7PNs9UjZ+UKW4PeOOsH7M35p7XNmWxbR4mZ3FMdtswgOyQm/tL9n6qyBMwMi11rMSBCumHsa9XlNtUgIfAnau8fFH/dC7vrt8Z2TRAxtWQf6omHsyrjr+YrP71HFKAEcE1joSBT7EGUFtRH/KxglDVkulNywPCa9Pae2UjUIW/IJKGq4XJ4bw15kzVszACS9PRjf4G7dTdQA25ICWq0L3bbmX+2FcVgsBZPo6Bs8KTrXPbDaBJdjYW5ch5tzLJU+YCOAiFBper7mG2ebIjqSKdUumguiYjQMIOf3fEEPPT3lzxuTtSbE2liSingKUwef12CB2ot00sB5MpBqa522wmdd3XvvQGxa2yeEb/cJrenjpLvTD/vszT1LkVSAxUPRqRXXDg94Gs95A/6qHRx/ve7/+7FxmcXI4+DJRfaP+UF7c8="

before_script:
  - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp .env.travis .env
  - sleep 10

before_install:
  - |
    INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # tpecl is a helper to compile and cache php extensions
      tpecl () {
          local ext_name=$1
          local ext_so=$2
          local ext_dir=$(php -r "echo ini_get('extension_dir');")
          local ext_cache=~/php-ext/$(basename $ext_dir)/$ext_name
          if [[ -e $ext_cache/$ext_so ]]; then
              echo extension = $ext_cache/$ext_so >> $INI
          else
              mkdir -p $ext_cache
              echo yes | pecl install -f $ext_name &&
              cp $ext_dir/$ext_so $ext_cache
          fi
      }
      export -f tpecl
  - tpecl mongodb-${DRIVER_VERSION} mongodb.so

# Install composer dependencies
install:
  - composer install
  - composer run-script install-codestandards

script:
  # run server
  - ./bin/console server:start
  # SensioLabs Security Checker: checks security issues
  - ./vendor/bin/security-checker security:check
  # PHP Lint: check syntax errors in all PHP files
  - ./vendor/bin/parallel-lint --no-colors --blame --exclude vendor .
  # PHP_CodeSniffer: check PHP compatibility
  - ./vendor/bin/phpcs -s --standard=PHPCompatibility src tests
  # PHP_CodeSniffer: check PSR2 standard
  - ./vendor/bin/phpcs -s --standard=PSR2 src tests
  # PHP Static Analysis Tool
  - ./vendor/bin/phpstan --no-ansi --no-progress analyse -c phpstan.neon -l 7 src tests
  # PHP unit tests
  - alias php='php -dzend_extension=xdebug.so'
  - ./vendor/bin/phpunit --version
  - ./vendor/bin/phpunit --testsuit Unit
  # Behat tests
  - ./vendor/bin/behat
  # SonarQube
  - sonar-scanner -X

# After a build, send email notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure: "lvjdb5liH9upaIXHVnKuUSBvWJAw5LBIknz/CT0lw6oC+Lq3nHryqMoa5VvIUCKlvmH9WPa9Y7/SY2KPX/3e9Zzu5YQLHA4qg0iRt2nNF1BEjRPpRf3hmEwaG5p9rDQrvgzJMeJmM6FRG2B4HPSs9WBCVRHI5H6oUaI7phlEGfATFWVsM1JvMSlL391ufHhJott/u4sxZf3Kr9KoWsdmdUfR1LijZd/x5dO+204V3dgCeI7+g74/I60Rj1AKE1/SzELmY4bnBFwB1ZkAVfVJ5ZrHkAVjdnLzuuOrGZEeieNBT7wc7espHHwX3hXecY3RLWENwMpGgh/FBa8X30LDLIUap/6/I3x24sJg3y53NL3kicFxiLCAeCsZE+7YgIcs5+dNpvOCx0A5m0ddGlSMLYFwnOHmJySjKkPEcLdmYOVe1W4ViUc4a3fhIhVQwLcWvK9PBGNBXcx/au74WNMgu+UoiqXsL6OsPIIUlz0SsXuXI1H24pN+ouZY7Uu0buxnZc0rJJo2pPAWJECVbcSpSgTs3T7B6mXpB8FLsoCYMCr1l1ESZOypiJWvxXbZU6YWGxZvFiGOsWkmkot9EaHppHaSnyfKrPZo6XNGrhg//LT1q2O0HpLf8k+qeoXE6VJmFcEaMfqDBTI8fnPKr9Qp4Mg2XOy+xJOJtjuET2X1b1Y="
    on_success: change
    on_failure: always
