# Project language
language: php

# PHP version
php:
  - 7.2

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install --no-ansi --no-scripts
  - composer run-script install-codestandards

stages:
  - build
  - quality
  - test

jobs:
  include:
    # PHP Lint: check syntax errors in all PHP files
    - stage: build
      script: ./bin/parallel-lint --no-colors --blame --exclude vendor .

    # PHP_CodeSniffer: check PHP compatibility
    - stage: quality
      script: ./bin/phpcs -s src --standard=PHPCompatibility

    # PHP_CodeSniffer: check PSR2 standard
    - stage: quality
      script: ./bin/phpcs -s src --standard=PSR2

    # PHP Static Analysis Tool
    - stage: quality
      script: ./bin/phpstan --no-ansi --no-progress analyse -c phpstan.neon -l 7 src

    # PHP unit tests
    - stage: test
      script:
        - alias php='php -dzend_extension=xdebug.so'
        - alias phpunit='php ./bin/phpunit'
        - phpunit
