user_registration:
  path: /register
  controller: Adshares\AdsOperator\Controller\Auth\AuthController::registerAction
  methods: [POST]

user_login:
  path: /login

user_change_email:
  path: /users/{id}/change-email
  controller: Adshares\AdsOperator\Controller\Auth\UserController::changeEmailAction
  methods: [POST]
