node_list:
    path: /nodes
    controller: Adshares\AdsOperator\Controller\Blockexplorer\NodeController:listAction
    methods: [GET]

block_list:
    path: /blocks
    controller: Adshares\AdsOperator\Controller\Blockexplorer\BlockController:listAction
    methods: [GET]
