Adshares\AdsOperator\Document\Message:
    exclusion_policy: ALL
    properties:
        transactionCount:
            expose: true
            type: int
        nodeId:
            expose: true
            type: string
