Adshares\Ads\Entity\Message:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
        node:
            expose: false
            type: int
        blockId:
            expose: true
            type: string
        hash:
            expose: true
            type: string
        length:
            expose: true
            type: int
        transactionCount:
            expose: true
            type: int
