index:
    path: /
    controller: Adshares\AdsOperator\Controller\DefaultController::index

blockexplorer:
    resource: "./routes/blockexplorer.yaml"
    type:     yaml
    prefix:   /api/%api_version%/blockexplorer/
