services:
  Adshares\AdsOperator\GuzzleHttp\ApiClient:
    class: GuzzleHttp\Client
    arguments: [ base_uri: '%env(API_URI)%' ]
    public: true

  Adshares\AdsOperator\Queue\QueueEngine:
    class: Adshares\AdsOperator\Queue\MemoryQueue
