Adshares\AdsOperator\Document\Account:
    type: document
    collection: account
    fields:
        id:
            id: true
            strategy: NONE
            type: string
        address:
            type: string
        balance:
            type: int
        hash:
            type: string
        localChange:
            type: date
        msid:
            type: int
        node:
            type: int
        pairedId:
            type: int
        pairedNode:
            type: int
        publicKey:
            type: string
        remoteChange:
            type: date
        status:
            type: int
        time:
            type: date

