Adshares\AdsOperator\Document\Account:
    type: document
    collection: account
    repositoryClass: Adshares\AdsOperator\Repository\Doctrine\AccountRepository
    fields:
        id:
            id: true
            strategy: NONE
            type: string
        address:
            type: string
        balance:
            type: int
        hash:
            type: string
        localChange:
            type: date
        msid:
            type: int
        node:
            type: int
        pairedAddress:
            type: string
        pairedNode:
            type: int
        publicKey:
            type: string
        remoteChange:
            type: date
        status:
            type: int
        time:
            type: date
    indexes:
        nodeid:
            keys:
                nodeId: desc
