Adshares\AdsOperator\Document\LocalTransaction:
  type: document
  collection: localTransaction
  repositoryClass: Adshares\AdsOperator\Repository\Doctrine\LocalTransactionRepository
  fields:
    id:
      id: true
      strategy: NONE
      type: string
    userId:
      type: string
    transactionId:
      type: string
    address:
      type: string
    type:
      type: string
    hash:
      type: string
    msid:
      type: int
    time:
      type: date
    data:
      type: string
    fee:
      type: int
    params:
      type: hash
