Adshares\AdsOperator\Document\Message:
    type: document
    collection: message
    repositoryClass: Adshares\AdsOperator\Repository\Doctrine\MessageRepository
    fields:
        id:
            id: true
            strategy: NONE
            type: string
        nodeId:
            type: string
        blockId:
            type: string
        hash:
            type: string
        length:
            type: string
        transactionCount:
            type: int




