Adshares\AdsOperator\Document\Transaction\KeyTransaction:
    type: document
    collection: transaction
    fields:
        id:
            id: true
            strategy: NONE
            type: string
        blockId:
            type: string
        messageId:
            type: string
        nodeId:
            type: string
        type:
            type: string
        size:
            type: int
        msgId:
            type: string
        newPublicKey:
            type: string
        oldPublicKey:
            type: string
        publicKey:
            type: string
        publicKeySignature:
            type: string
        targetNode:
            type: string
        targetUser:
            type: string
        node:
            type: int
        signature:
            type: string
        time:
            type: date
        user:
            type: int
        targetAddress:
            type: string
        senderAddress:
            type: string
