Adshares\AdsOperator\Document\Transaction\ConnectionTransaction:
    type: document
    collection: transaction
    fields:
        id:
            id: true
            strategy: NONE
            type: string
        blockId:
            type: string
        messageId:
            type: string
        nodeId:
            type: string
        type:
            type: string
        size:
            type: int
        ipAddress:
            type: string
        port:
            type: int
