Adshares\AdsOperator\Document\Transaction\BroadcastTransaction:
    type: document
    collection: transaction
    fields:
        id:
            id: true
            strategy: NONE
            type: string
        blockId:
            type: string
        messageId:
            type: string
        nodeId:
            type: string
        type:
            type: string
        size:
            type: int
        message:
            type: string
        messageLength:
            type: int
        msgId:
            type: string
        node:
            type: int
        signature:
            type: string
        time:
            type: date
        user:
            type: int
        senderAddress:
            type: string
