Adshares\AdsOperator\Document\Transaction\SendManyTransactionWire:
    type: embeddedDocument
    fields:
        amount:
            type: string
        targetAddress:
            type: string
        targetNode:
            type: int
        targetUser:
            type: int
